name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "574797fc249d1fb40d8e12b09cc5a1a3ee4997b48c5a685d3ee2f19febcb79e0"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
