name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e7ae3ffebeae41f6d4faa324940715f4f461490494ef2188bf4468bcd394941"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
