name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb0346354b562c42aaed9ae62c5fc180547a207ce31b604d256de4bf4be56546"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
