name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d461fc33341d52ae2042b9732577b41a45df7a6d862058da1e3b60a9a0819166"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
