name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a03c399f3975da4321f397c37f016dbf7404e75349fdd4230f155d9f44a86e"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
