name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "442d2f5b63ba425a21fd4447316ca6ca072c01dac431e049b88d50b3e02c1e65"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
