name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b70eb38ab017d86e546fb54496facdc0d8070d45120c42c39575e9d5aa22776e"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
