name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39a48999cb862aab26d063d7be9b49b92f523476feaa48bfdec139e255e2a1f0"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
