name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6e9a67dc21c957b6b040edda4ca55f1a6d32455fb48b6d0772977d2e9a17547"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
