name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe7cc5c90b3ec71984ccadc2135742fc9061d860701aab0916536309c2fa545"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
