name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf48efd32ca9bec1ba2edd0450e06dca7f3f85e1f8bcc35a535fde6f56546dfe"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
