name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e14c0690cd9fb1c1a9352eaa277d9f13fd08d09166659cc933cbc123575de300"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
