name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2437b77227d24852b8127f2711762365c97e29f534226272341934c2d7532834"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
