name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c3d059ff44943e7c45fb290faac0d5aec0770d45e31b950d8a4aa5a66d5fef"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
