name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f3d42f0d0f938985b73acd5560ff00d92d04976d93333e739da64ce75bc181c"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
