name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d166a03dd7d287f49959ada977100e73ea399320b9ef90831253ff7f97d19f31"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
