name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2909fff549b89bba17b09e3928988d72b6f8abf0f33e1fde35b1bd78d80a1fc1"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
