name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f71a93594b121a6b0db219c561d6b5eff5b9883b01e133335ffd1e3fde0512d5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
