name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "580d9773ae5da94ed5d8fd25f7923c9c0d915949c687e0d2ba89355ef8cbf170"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
