name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f851fba96c1e83f4476b1851c0455a39e52d26ccfec5f2e050cf6ae346efb48"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
