name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ee2346e2fb095671a998c7864709f5fb2479e9bd0e74efaf4495799dcc62e1a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
