name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dca231904ba3fe7d7a2f1c2de27edf201e2830ac514503a103c00ff803c2eaf5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
