name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41b44a8920f309d189a70fda1147fdf4c91170c247301f71e0c8832d27c0c039"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
