name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f38902fb16add4a9609703b97451d8a406350b9cff41868c609bea0265c1ccb"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
