name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "965693aec4828213880e7ee3131a66d89d101cf5d6939ce573d60feb5c04f08c"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
