name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "004f625751f84a9d2b437408bd5bc80c0dfd29bdc3ebceee9556e8f1cf0d4926"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
