name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "800343dcac9aff2d12f8a9d05ab53eb6c65b368082dfa3ab0a37466edf69989a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
