name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06bdc0f5db5890c179493e07682b9879815e3ca917dcb31203edc468f564a9a6"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
