name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b083328a2b93e8b9bc6aece9f1b304826c1bdfdfcd762a4032b31800d01774b5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
