name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e707b134abbea60b4a292b25f7474ebf68571e37f8deb68f0a708652b7bb81fd"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
