name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "344d81ee09817eaec580b3023c4352715d89afbc85913ee55e3b2cbe3f4eecda"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
