name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b486fb21538a4ac5c3a62768f16323a6e3d9b515dd2e34358a881850b8e3d69a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
