name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c11ad7b68ecfc0c37e0cc4920de90f98ce1c88675eaaa78866de35bcef9a284"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
