name = "Hexserver 3 Mods"
author = "Walksanator"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b0090f3e4c8e45379add50966a999939351d4ac9e02f73ccffa2cfe01e1edd6"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
