name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed944b417a95f7bddb09175e84c9fec27597689cd2ecc4338414cda8c3847a00"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "resources"
