name: Merge schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # every day at 14:45 UTC
    - cron: '45 14 * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: merge
          time_zone: 'America/Toronto'
          require_statuses_success: 'false'
          automerge_fail_label: 'automerge-fail'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}