name: Merge schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # every day at 1:45 and 13:45 UTC
    - cron: '40 1,13 * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: merge
          require_statuses_success: 'false'
          automerge_fail_label: 'automerge-fail'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
