name: Merge schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # every day at 2:45 and 14:45 UTC
    - cron: '45 2,14 * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: merge
          require_statuses_success: 'false'
          automerge_fail_label: 'automerge-fail'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
