name: Ensure Packwiz has been refreshed

on: [push]

jobs:
  packwiz_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Refresh index
        run: ./packwiz/packwiz refresh

      - name: Ensure the refresh had no effect
        run: git diff --exit-code
