name: Refresh Packwiz

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  packwiz_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.repository }}
      
      - name: Refresh index
        run: ./packwiz/packwiz refresh

      - name: Commit updated index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Refresh Packwiz index
