name: Ensure Packwiz has been refreshed

on: [push]

jobs:
  packwiz_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Packwiz
        uses: engineerd/configurator@v0.0.9
        with:
          name: packwiz
          url: https://github.com/packwiz/packwiz/suites/13275029231/artifacts/724180287
          pathInArchive: packwiz
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Refresh index
        run: packwiz refresh

      - name: Ensure the refresh had no effect
        run: git diff --exit-code
